export function dashboardHtml(): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>AntroSwarm Control Center</title>
<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#090b10;color:#e9edf5}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#172033 0,#090b10 45%);min-height:100vh}.wrap{max-width:1200px;margin:auto;padding:28px}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:22px}.brand{font-weight:800;font-size:26px}.muted{color:#8e9bb0}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}.panel{background:rgba(15,19,28,.88);border:1px solid #273044;border-radius:16px;padding:18px;box-shadow:0 16px 50px rgba(0,0,0,.25)}h2{margin:0 0 14px;font-size:16px}label{display:block;font-size:12px;color:#9aa7bb;margin:12px 0 6px}select,input,textarea,button{width:100%;border-radius:10px;border:1px solid #303a50;background:#0d1119;color:#eef3fb;padding:10px 12px;font:inherit}textarea{min-height:160px;resize:vertical}button{cursor:pointer;background:#5b7cff;border:0;font-weight:700;margin-top:12px}button.secondary{background:#20283a}.agents{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}.agent{border:1px solid #293247;background:#0c111a;border-radius:12px;padding:12px}.dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:7px}.online{background:#4fd18b}.offline{background:#687386}.cmd{border-top:1px solid #242c3d;padding:12px 0}.cmd:first-child{border-top:0}.status{display:inline-block;padding:3px 7px;border-radius:999px;background:#202a3c;font-size:11px;margin:2px}.queued{color:#f3c969}.delivered{color:#7fc8ff}.running{color:#9fa9ff}.done{color:#63dc9a}.failed{color:#ff7e89}.row{display:flex;gap:10px}.row>*{flex:1}.small{font-size:12px;word-break:break-word}.toast{position:fixed;right:20px;bottom:20px;background:#172133;border:1px solid #34425f;padding:12px 16px;border-radius:10px;display:none}@media(max-width:850px){.grid{grid-template-columns:1fr}.wrap{padding:16px}}
</style>
</head>
<body><div class="wrap">
<div class="top"><div><div class="brand">AntroSwarm Control Center</div><div class="muted">Broadcast prompts, target one agent, watch delivery and execution.</div></div><div id="runnerCount" class="muted">runner: —</div></div>
<div class="grid">
<section class="panel"><h2>Send command</h2><label>Swarm</label><select id="swarm"></select><label>Target</label><select id="target"></select><label>Label (optional)</label><input id="label" placeholder="implementation phase"/><label>Prompt</label><textarea id="prompt" placeholder="What should the agent(s) do next?"></textarea><button id="send">Send command</button><button class="secondary" id="copyWorker">Copy worker prompt</button><div class="muted small" style="margin-top:10px">Worker mode can keep polling while a ChatGPT turn remains active. Finished ChatGPT turns still cannot be externally awakened.</div></section>
<section class="panel"><h2>Agents</h2><div id="agents" class="agents"></div></section>
<section class="panel" style="grid-column:1/-1"><div class="row"><h2 style="flex:1">Command queue</h2><button class="secondary" id="refresh" style="width:auto;margin:0">Refresh</button></div><div id="commands"></div></section>
</div></div><div id="toast" class="toast"></div>
<script>
const qs=new URLSearchParams(location.search);const token=qs.get('token')||'';const api=(p)=>p+(token?(p.includes('?')?'&':'?')+'token='+encodeURIComponent(token):'');let snapshot=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(v){const e=document.getElementById('toast');e.textContent=v;e.style.display='block';setTimeout(()=>e.style.display='none',2200)}
function currentSwarm(){return document.getElementById('swarm').value}
async function load(){const selected=currentSwarm();const r=await fetch(api('/api/dashboard'));if(!r.ok)throw new Error(await r.text());snapshot=await r.json();const sw=document.getElementById('swarm');sw.innerHTML=snapshot.swarms.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.id)+'</option>').join('');if(selected&&snapshot.swarms.some(s=>s.id===selected))sw.value=selected;render();}
function render(){const s=snapshot.swarms.find(x=>x.id===currentSwarm())||snapshot.swarms[0];if(!s)return;const target=document.getElementById('target');const prev=target.value;target.innerHTML='<option value="all">All agents</option>'+s.agents.map(a=>'<option value="'+esc(a.id)+'">'+esc(a.displayName)+' · '+esc(a.id)+'</option>').join('');if([...target.options].some(o=>o.value===prev))target.value=prev;document.getElementById('agents').innerHTML=s.agents.map(a=>'<div class="agent"><div><span class="dot '+(a.online?'online':'offline')+'"></span><b>'+esc(a.displayName)+'</b></div><div class="muted small">'+esc(a.id)+'</div><div class="small">task: '+esc(a.currentTaskId||'—')+'</div><div class="small">branch: '+esc(a.branch||'—')+'</div><div class="muted small">seen '+Math.round(a.ageMs/1000)+'s ago</div></div>').join('');document.getElementById('runnerCount').textContent='runners: '+snapshot.runners.length;const cmds=snapshot.commands.filter(c=>c.swarmId===s.id).slice().reverse();document.getElementById('commands').innerHTML=cmds.length?cmds.map(c=>'<div class="cmd"><div><b>'+esc(c.label||c.id)+'</b> <span class="muted small">'+new Date(c.createdAt).toLocaleTimeString()+'</span></div><div class="small" style="margin:6px 0">'+esc(c.prompt).slice(0,600)+'</div><div>'+Object.entries(c.deliveries).map(([id,d])=>'<span class="status '+esc(d.status)+'">'+esc((s.agents.find(a=>a.id===id)||{}).displayName||id)+': '+esc(d.status)+'</span>').join('')+'</div></div>').join(''):'<div class="muted">No commands yet.</div>'}
document.getElementById('swarm').addEventListener('change',render);document.getElementById('refresh').addEventListener('click',()=>load().catch(e=>toast(e.message)));document.getElementById('send').addEventListener('click',async()=>{const body={swarm_id:currentSwarm(),target:document.getElementById('target').value,label:document.getElementById('label').value,prompt:document.getElementById('prompt').value};const r=await fetch(api('/api/commands'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok){toast(await r.text());return}document.getElementById('prompt').value='';toast('Command queued');await load()});document.getElementById('copyWorker').addEventListener('click',async()=>{const s=currentSwarm();const text='Use AntroSwarm. You are already connected to swarm '+s+'. Enter worker mode: repeatedly call swarm_wait with wait_ms=20000. When a command arrives, call swarm_ack, execute the command, then call swarm_report with done or failed and a concise result. Continue polling while this turn remains active. Do not create a new identity.';await navigator.clipboard.writeText(text);toast('Worker prompt copied')});load().catch(e=>toast(e.message));setInterval(()=>load().catch(()=>{}),2000);
</script></body></html>`;
}
